# Generated by Django 6.0.4 on 2026-04-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
    ]
